all:
	make -C python_hildon_manual html
	make -C python_hildon_tutorial html
	make -C python_location_manual html
	make -C www html

clean:
	make -C python_hildon_manual clean
	make -C python_hildon_tutorial clean
	make -C python_location_manual clean
	make -C www clean
