all:
	cd python_hildon_manual && make html && cd ..
	cd python_hildon_tutorial && make html && cd ..
	cd www && make html && cd ..

clean:
	cd python_hildon_manual && make clean && cd ..
	cd python_hildon_tutorial && make clean && cd ..
	cd www && make clean && cd ..
